apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment # Name of the deployment
spec:
  selector:
    matchLabels:
      app: mssql # Label to identify the pods managed by this deployment
  template:
    metadata:
      labels:
        app: mssql # Label to identify the pods managed by this deployment
    spec:
      containers:
      - name: mssql # Name of the container
        image: mcr.microsoft.com/mssql/server:2022-latest # SQL Server Docker image
        ports:
        - containerPort: 1433 # Port the container listens on
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret # Reference to the secret containing the SA password
              key: SA_PASSWORD
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -C -Q "SELECT 1"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1"
        volumeMounts:
        - name: mssql-storage
          mountPath: /var/opt/mssql # Mount path for the persistent volume
      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: mssql-pvc # Reference to the persistent volume claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service # Name of the service
spec:
  selector:
    app: mssql # Label to identify the pods managed by this service
  ports:
  - protocol: TCP
    port: 1433 # Port the service listens on
    targetPort: 1433 # Port the container listens on
